version: "3"
services:
  reverseproxy:
    image: sshruti14/reverseproxy
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - backend-user
      - backend-feed
  backend-user:
    image: sshruti14/udagram-restapi-user
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  backend-feed:
    image: sshruti14/udagram-restapi-feed
    
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD     
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  frontend:
    image: sshruti14/udagram-frontend
    ports:
      - 8100:80

      